In [64]:
import pandas as pd

In [94]:
data = pd.read_csv('BRO 2 (Zomato) Sort file.csv')

In [95]:
data.head()

,Restaurant_Name,Locality,Sponsored,Ratings_out_of_5,Number of votes,Cuisines,Charges_for_two,payment_modes,Rest_timming,5_star_review_percentage,4_star_review_percentage,3_star_review_percentage,2_star_review_percentage,1_star_review_percentage
0,Lager Street - Lounge and Bar,Balewadi,Lounge,4.0,Based on 168 votes,"Bar Food, Continental, Italian, North Indian","₹1,500",Cash and Cards accepted,12noon – 12:30am,62%,18%,7%,3%,10%
1,Deewan Khana,Balewadi,"Casual Dining, Bar",4.1,262 votes,"Seafood, Maharashtrian","₹1,400","Cash,Cards and Digital Payments accepted",11am – 12midnight,53%,28%,6%,3%,10%
2,D'nozzo Chinese Food Hub,Balewadi,"Takeaway, Delivery",3.7,Based on 66 votes,Chinese,Not Present,"Cash,Cards and Digital Payments accepted","12noon – 3:30pm, 6:30pm – 12midnight",91%,6%,3%,0%,0%
3,Zura Sizzler Kitchen,Balewadi,Casual Dining,0.0,0,"Continental, Asian, Beverages","₹1,500",Cash and Cards accepted,"12:01pm – 3:30pm, 7pm – 11pm",0,0,0,0,0
4,Nirvighnam,Balewadi,Casual Dining,3.6,81 votes,"North Indian, South Indian",₹700,Cash and Cards accepted,"8:30am – 3:30pm, 7pm – 11:30pm",81%,11%,2%,1%,5%

In [96]:
data

,Restaurant_Name,Locality,Sponsored,Ratings_out_of_5,Number of votes,Cuisines,Charges_for_two,payment_modes,Rest_timming,5_star_review_percentage,4_star_review_percentage,3_star_review_percentage,2_star_review_percentage,1_star_review_percentage
0,Lager Street - Lounge and Bar,Balewadi,Lounge,4.0,Based on 168 votes,"Bar Food, Continental, Italian, North Indian","₹1,500",Cash and Cards accepted,12noon – 12:30am,62%,18%,7%,3%,10%
1,Deewan Khana,Balewadi,"Casual Dining, Bar",4.1,262 votes,"Seafood, Maharashtrian","₹1,400","Cash,Cards and Digital Payments accepted",11am – 12midnight,53%,28%,6%,3%,10%
2,D'nozzo Chinese Food Hub,Balewadi,"Takeaway, Delivery",3.7,Based on 66 votes,Chinese,Not Present,"Cash,Cards and Digital Payments accepted","12noon – 3:30pm, 6:30pm – 12midnight",91%,6%,3%,0%,0%
3,Zura Sizzler Kitchen,Balewadi,Casual Dining,0.0,0,"Continental, Asian, Beverages","₹1,500",Cash and Cards accepted,"12:01pm – 3:30pm, 7pm – 11pm",0,0,0,0,0
4,Nirvighnam,Balewadi,Casual Dining,3.6,81 votes,"North Indian, South Indian",₹700,Cash and Cards accepted,"8:30am – 3:30pm, 7pm – 11:30pm",81%,11%,2%,1%,5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1320,Teera Farms,Wakad,Casual Dining,0.0,0,"North Indian, Chinese, Continental",₹800,Cash and Cards accepted,1pm – 3am,0,0,0,0,0
1321,Restro The Pasta,Wakad,"Takeaway, Delivery",0.0,0,Fast Food,Not Present,Cash only,11am – 11pm,0,0,0,0,0
1322,Superman's Cafe,Wakad,Café,0.0,0,"Cafe, Fast Food, South Indian",₹150,Cash and Digital Payments accepted,9am – 1am,0,0,0,0,0
1323,Not Just Parathas,Wakad,Delivery,0.0,0,North Indian,Not Present,Cash only,11am – 11pm,0,0,0,0,0
1324,Southentic,Wakad,Delivery,0.0,0,South Indian,Not Present,Cash only,10am – 11pm,0,0,0,0,0

In [97]:
data.describe()

       Ratings_out_of_5
count       1325.000000
mean           3.066113
std            1.200959
min            0.000000
25%            3.000000
50%            3.400000
75%            3.700000
max            4.900000

In [98]:
data.columns

Index(['Restaurant_Name', 'Locality', 'Sponsored', 'Ratings_out_of_5',
       'Number of votes', 'Cuisines', 'Charges_for_two', 'payment_modes',
       'Rest_timming', '5_star_review_percentage', '4_star_review_percentage',
       '3_star_review_percentage', '2_star_review_percentage',
       '1_star_review_percentage'],
      dtype='object')

In [99]:
data.describe()

       Ratings_out_of_5
count       1325.000000
mean           3.066113
std            1.200959
min            0.000000
25%            3.000000
50%            3.400000
75%            3.700000
max            4.900000

In [100]:
data1 = data['loc']

KeyError: 'loc'

In [101]:
data1

0                 The Westin, Mundhwa
1                 The Westin, Mundhwa
2       Conrad Pune, Bund Garden Road
3                 The Westin, Mundhwa
4             Vivanta Pune, Hinjewadi
                    ...
5428                     Sinhgad Road
5429                      Viman Nagar
5430                           Pimpri
5431                    Sadashiv Peth
5432                 B.T. Kawade Road
Name: loc, Length: 5433, dtype: object

In [102]:
data.count()

Restaurant_Name             1325
Locality                    1325
Sponsored                   1325
Ratings_out_of_5            1325
Number of votes             1325
Cuisines                    1325
Charges_for_two             1325
payment_modes               1325
Rest_timming                1325
5_star_review_percentage    1325
4_star_review_percentage    1325
3_star_review_percentage    1325
2_star_review_percentage    1325
1_star_review_percentage    1325
dtype: int64

In [103]:
data.max()

Restaurant_Name                                                  eSSSetrra
Locality                                                             Wakad
Sponsored                                               Takeaway, Delivery
Ratings_out_of_5                                                       4.9
Number of votes                                       Na základě 230 hlasů
Cuisines                                       Wraps, Fast Food, Beverages
Charges_for_two                                                       ₹900
payment_modes               Cash,Debit Cards and Digital Payments accepted
Rest_timming                                                        Closed
5_star_review_percentage                                               98%
4_star_review_percentage                                                9%
3_star_review_percentage                                                9%
2_star_review_percentage                                                9%
1_star_review_percentage                                                9%
dtype: object

In [104]:
data.min()

Restaurant_Name                100 Rupis.com Burgers & More
Locality                                           Balewadi
Sponsored                                            Bakery
Ratings_out_of_5                                          0
Number of votes                                           0
Cuisines                    American, Chinese, North Indian
Charges_for_two                                 Not Present
payment_modes                       Cash and Cards accepted
Rest_timming                              10:15am – 11:45pm
5_star_review_percentage                                  0
4_star_review_percentage                                  0
3_star_review_percentage                                  0
2_star_review_percentage                                  0
1_star_review_percentage                                  0
dtype: object

In [105]:
print(data.isnull().count())

Restaurant_Name             1325
Locality                    1325
Sponsored                   1325
Ratings_out_of_5            1325
Number of votes             1325
Cuisines                    1325
Charges_for_two             1325
payment_modes               1325
Rest_timming                1325
5_star_review_percentage    1325
4_star_review_percentage    1325
3_star_review_percentage    1325
2_star_review_percentage    1325
1_star_review_percentage    1325
dtype: int64

In [106]:
balewadi = data.loc[:, ['Locality' = 'Balewadi', 'Ratings_out_of_5']]

SyntaxError: invalid syntax (<ipython-input-106-34e61a90cdcb>, line 1)

In [107]:
balewadi

,Restaurant_Name,Locality,Sponsored,Ratings_out_of_5,Number of votes,Cuisines,Charges_for_two,payment_modes,Rest_timming,5_star_review_percentage,4_star_review_percentage,3_star_review_percentage,2_star_review_percentage,1_star_review_percentage
0,Lager Street - Lounge and Bar,Balewadi,Lounge,4.0,Based on 168 votes,"Bar Food, Continental, Italian, North Indian","₹1,500",Cash and Cards accepted,12noon – 12:30am,62%,18%,7%,3%,10%
1,Deewan Khana,Balewadi,"Casual Dining, Bar",4.1,262 votes,"Seafood, Maharashtrian","₹1,400","Cash,Cards and Digital Payments accepted",11am – 12midnight,53%,28%,6%,3%,10%
2,D'nozzo Chinese Food Hub,Balewadi,"Takeaway, Delivery",3.7,Based on 66 votes,Chinese,Not Present,"Cash,Cards and Digital Payments accepted","12noon – 3:30pm, 6:30pm – 12midnight",91%,6%,3%,0%,0%
3,Zura Sizzler Kitchen,Balewadi,Casual Dining,0.0,0,"Continental, Asian, Beverages","₹1,500",Cash and Cards accepted,"12:01pm – 3:30pm, 7pm – 11pm",0,0,0,0,0
4,Nirvighnam,Balewadi,Casual Dining,3.6,81 votes,"North Indian, South Indian",₹700,Cash and Cards accepted,"8:30am – 3:30pm, 7pm – 11:30pm",81%,11%,2%,1%,5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,Jojo's Kitchen,Balewadi,Casual Dining,3.6,92 votes,"North Indian, Mughlai, Wraps, Biryani",₹700,"Cash,Cards and Digital Payments accepted","12noon – 3:30pm, 7pm – 11:30pm",57%,15%,11%,2%,15%
101,Blue Box Biryani,Balewadi,Delivery,0.0,0,"Biryani, Kebab",Not Present,Cash only,11am – 11pm,0,0,0,0,0
102,China Magic,Balewadi,"Takeaway, Delivery",0.0,0,Chinese,Not Present,Cash only,"12noon – 3:30pm, 6:30pm – 12midnight",0,0,0,0,0
103,Cafe Cream,Balewadi,Quick Bites,0.0,0,"Sandwich, Burger, Fast Food",₹300,Cash and Digital Payments accepted,11:30am – 11pm,0,0,0,0,0
104,Cafe Creamy Nuts,Balewadi,Café,0.0,0,"Coffee, Fast Food",₹150,"Cash,Cards and Digital Payments accepted",10am – 11pm,0,0,0,0,0

In [108]:

new_dataset = data[['Locality','Ratings_out_of_5']]

In [109]:
new_dataset

      Locality  Ratings_out_of_5
0     Balewadi               4.0
1     Balewadi               4.1
2     Balewadi               3.7
3     Balewadi               0.0
4     Balewadi               3.6
...        ...               ...
1320     Wakad               0.0
1321     Wakad               0.0
1322     Wakad               0.0
1323     Wakad               0.0
1324     Wakad               0.0

[1325 rows x 2 columns]

In [110]:
df9 = data.groupby('Locality')['Ratings_out_of_5'].sum()

In [111]:
df9

Locality
Balewadi      295.5
Baner        1114.2
Bavdhan       420.1
Hinjawadi    1065.4
Wakad        1167.4
Name: Ratings_out_of_5, dtype: float64

In [112]:
balewadi = data[(data.Locality.str.contains('Balewadi'))]
Baner = data[(data.Locality.str.contains('Baner'))]
Bavdhan = data[(data.Locality.str.contains('Bavdhan'))]
Hinjawadi = data[(data.Locality.str.contains('Hinjawadi'))]
Wakad = data[(data.Locality.str.contains('Wakad'))]

In [115]:
balewadi

,Restaurant_Name,Locality,Sponsored,Ratings_out_of_5,Number of votes,Cuisines,Charges_for_two,payment_modes,Rest_timming,5_star_review_percentage,4_star_review_percentage,3_star_review_percentage,2_star_review_percentage,1_star_review_percentage
0,Lager Street - Lounge and Bar,Balewadi,Lounge,4.0,Based on 168 votes,"Bar Food, Continental, Italian, North Indian","₹1,500",Cash and Cards accepted,12noon – 12:30am,62%,18%,7%,3%,10%
1,Deewan Khana,Balewadi,"Casual Dining, Bar",4.1,262 votes,"Seafood, Maharashtrian","₹1,400","Cash,Cards and Digital Payments accepted",11am – 12midnight,53%,28%,6%,3%,10%
2,D'nozzo Chinese Food Hub,Balewadi,"Takeaway, Delivery",3.7,Based on 66 votes,Chinese,Not Present,"Cash,Cards and Digital Payments accepted","12noon – 3:30pm, 6:30pm – 12midnight",91%,6%,3%,0%,0%
3,Zura Sizzler Kitchen,Balewadi,Casual Dining,0.0,0,"Continental, Asian, Beverages","₹1,500",Cash and Cards accepted,"12:01pm – 3:30pm, 7pm – 11pm",0,0,0,0,0
4,Nirvighnam,Balewadi,Casual Dining,3.6,81 votes,"North Indian, South Indian",₹700,Cash and Cards accepted,"8:30am – 3:30pm, 7pm – 11:30pm",81%,11%,2%,1%,5%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
100,Jojo's Kitchen,Balewadi,Casual Dining,3.6,92 votes,"North Indian, Mughlai, Wraps, Biryani",₹700,"Cash,Cards and Digital Payments accepted","12noon – 3:30pm, 7pm – 11:30pm",57%,15%,11%,2%,15%
101,Blue Box Biryani,Balewadi,Delivery,0.0,0,"Biryani, Kebab",Not Present,Cash only,11am – 11pm,0,0,0,0,0
102,China Magic,Balewadi,"Takeaway, Delivery",0.0,0,Chinese,Not Present,Cash only,"12noon – 3:30pm, 6:30pm – 12midnight",0,0,0,0,0
103,Cafe Cream,Balewadi,Quick Bites,0.0,0,"Sandwich, Burger, Fast Food",₹300,Cash and Digital Payments accepted,11:30am – 11pm,0,0,0,0,0
104,Cafe Creamy Nuts,Balewadi,Café,0.0,0,"Coffee, Fast Food",₹150,"Cash,Cards and Digital Payments accepted",10am – 11pm,0,0,0,0,0

In [114]:
df44

0       False
1       False
2       False
3       False
4       False
        ...
5428    False
5429    False
5430    False
5431    False
5432    False
Name: loc, Length: 5433, dtype: bool